2023-05-08 10:49:17,087 INFO    StreamThr :21796 [internal.py:wandb_internal():86] W&B internal server running at pid: 21796, started at: 2023-05-08 10:49:17.087069
2023-05-08 10:49:17,088 DEBUG   HandlerThread:21796 [handler.py:handle_request():144] handle_request: status
2023-05-08 10:49:17,089 INFO    WriterThread:21796 [datastore.py:open_for_write():85] open: D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\run-tsapypnn.wandb
2023-05-08 10:49:17,090 DEBUG   SenderThread:21796 [sender.py:send():375] send: header
2023-05-08 10:49:17,091 DEBUG   SenderThread:21796 [sender.py:send():375] send: run
2023-05-08 10:49:17,814 INFO    SenderThread:21796 [dir_watcher.py:__init__():219] watching files in: D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files
2023-05-08 10:49:17,816 INFO    SenderThread:21796 [sender.py:_start_run_threads():1124] run started: tsapypnn with start time 1683514157.087068
2023-05-08 10:49:17,816 DEBUG   SenderThread:21796 [sender.py:send_request():402] send_request: summary_record
2023-05-08 10:49:17,817 INFO    SenderThread:21796 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-05-08 10:49:17,821 DEBUG   HandlerThread:21796 [handler.py:handle_request():144] handle_request: check_version
2023-05-08 10:49:17,822 DEBUG   SenderThread:21796 [sender.py:send_request():402] send_request: check_version
2023-05-08 10:49:18,543 DEBUG   HandlerThread:21796 [handler.py:handle_request():144] handle_request: run_start
2023-05-08 10:49:18,834 INFO    Thread-16 :21796 [dir_watcher.py:_on_file_created():278] file/dir created: D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\wandb-summary.json
2023-05-08 10:49:20,036 DEBUG   HandlerThread:21796 [system_info.py:__init__():31] System info init
2023-05-08 10:49:20,036 DEBUG   HandlerThread:21796 [system_info.py:__init__():46] System info init done
2023-05-08 10:49:20,036 INFO    HandlerThread:21796 [system_monitor.py:start():181] Starting system monitor
2023-05-08 10:49:20,036 INFO    SystemMonitor:21796 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-05-08 10:49:20,037 INFO    HandlerThread:21796 [system_monitor.py:probe():201] Collecting system info
2023-05-08 10:49:20,041 INFO    SystemMonitor:21796 [interfaces.py:start():190] Started cpu monitoring
2023-05-08 10:49:20,041 INFO    SystemMonitor:21796 [interfaces.py:start():190] Started disk monitoring
2023-05-08 10:49:20,041 INFO    SystemMonitor:21796 [interfaces.py:start():190] Started gpu monitoring
2023-05-08 10:49:20,046 INFO    SystemMonitor:21796 [interfaces.py:start():190] Started memory monitoring
2023-05-08 10:49:20,056 INFO    SystemMonitor:21796 [interfaces.py:start():190] Started network monitoring
2023-05-08 10:49:20,066 DEBUG   HandlerThread:21796 [system_info.py:probe():195] Probing system
2023-05-08 10:49:20,067 DEBUG   HandlerThread:21796 [git.py:repo():40] git repository is invalid
2023-05-08 10:49:20,067 DEBUG   HandlerThread:21796 [system_info.py:probe():240] Probing system done
2023-05-08 10:49:20,067 DEBUG   HandlerThread:21796 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.19044-SP0', 'python': '3.8.13', 'heartbeatAt': '2023-05-08T02:49:20.066590', 'startedAt': '2023-05-08T02:49:17.065675', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'D:/pycharm/Projects/DRL-MTSP-main/playground.py', 'codePath': 'playground.py', 'host': 'MSI', 'username': '63218', 'executable': 'D:\\Anaconda\\envs\\VRP\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 2301.0, 'min': 0.0, 'max': 2301.0}, 'cpu_freq_per_core': [{'current': 2301.0, 'min': 0.0, 'max': 2301.0}], 'disk': {'total': 151.18261337280273, 'used': 113.95611572265625}, 'gpu': 'NVIDIA GeForce RTX 3070 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3070 Laptop GPU', 'memory_total': 8589934592}], 'memory': {'total': 15.708480834960938}}
2023-05-08 10:49:20,067 INFO    HandlerThread:21796 [system_monitor.py:probe():211] Finished collecting system info
2023-05-08 10:49:20,067 INFO    HandlerThread:21796 [system_monitor.py:probe():214] Publishing system info
2023-05-08 10:49:20,067 DEBUG   HandlerThread:21796 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-05-08 10:49:20,069 ERROR   gpu       :21796 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-05-08 10:49:20,079 DEBUG   HandlerThread:21796 [system_info.py:_save_pip():67] Saving pip packages done
2023-05-08 10:49:20,079 DEBUG   HandlerThread:21796 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-05-08 10:49:20,849 INFO    Thread-16 :21796 [dir_watcher.py:_on_file_created():278] file/dir created: D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\conda-environment.yaml
2023-05-08 10:49:20,849 INFO    Thread-16 :21796 [dir_watcher.py:_on_file_created():278] file/dir created: D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\requirements.txt
2023-05-08 10:49:21,859 INFO    Thread-16 :21796 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\conda-environment.yaml
2023-05-08 10:49:21,917 DEBUG   HandlerThread:21796 [system_info.py:_save_conda():86] Saving conda packages done
2023-05-08 10:49:21,918 INFO    HandlerThread:21796 [system_monitor.py:probe():216] Finished publishing system info
2023-05-08 10:49:22,566 INFO    SenderThread:21796 [sender.py:finish():1550] shutting down sender
2023-05-08 10:49:22,566 INFO    SenderThread:21796 [dir_watcher.py:finish():365] shutting down directory watcher
2023-05-08 10:49:22,865 INFO    WriterThread:21796 [datastore.py:close():298] close: D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\run-tsapypnn.wandb
2023-05-08 10:49:22,866 INFO    SenderThread:21796 [dir_watcher.py:_on_file_modified():295] file/dir modified: D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\conda-environment.yaml
2023-05-08 10:49:22,866 INFO    SenderThread:21796 [dir_watcher.py:_on_file_created():278] file/dir created: D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\wandb-metadata.json
2023-05-08 10:49:22,866 INFO    SenderThread:21796 [dir_watcher.py:finish():395] scan: D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files
2023-05-08 10:49:22,866 INFO    SenderThread:21796 [dir_watcher.py:finish():409] scan save: D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\conda-environment.yaml conda-environment.yaml
2023-05-08 10:49:22,867 INFO    SenderThread:21796 [dir_watcher.py:finish():409] scan save: D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\config.yaml config.yaml
2023-05-08 10:49:22,867 ERROR   gpu       :21796 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-05-08 10:49:22,869 ERROR   gpu       :21796 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-05-08 10:49:22,869 INFO    SenderThread:21796 [dir_watcher.py:finish():409] scan save: D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\requirements.txt requirements.txt
2023-05-08 10:49:22,870 INFO    SenderThread:21796 [dir_watcher.py:finish():409] scan save: D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\wandb-metadata.json wandb-metadata.json
2023-05-08 10:49:22,870 INFO    SenderThread:21796 [dir_watcher.py:finish():409] scan save: D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\wandb-summary.json wandb-summary.json
2023-05-08 10:49:22,874 INFO    SenderThread:21796 [file_pusher.py:finish():168] shutting down file pusher
2023-05-08 10:49:22,874 INFO    SenderThread:21796 [file_pusher.py:join():173] waiting for file pusher
2023-05-08 10:49:23,650 INFO    wandb-upload_0:21796 [upload_job.py:push():137] Uploaded file D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\conda-environment.yaml
2023-05-08 10:49:23,762 INFO    wandb-upload_4:21796 [upload_job.py:push():137] Uploaded file D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\wandb-summary.json
2023-05-08 10:49:23,772 INFO    wandb-upload_2:21796 [upload_job.py:push():137] Uploaded file D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\requirements.txt
2023-05-08 10:49:23,794 INFO    wandb-upload_3:21796 [upload_job.py:push():137] Uploaded file D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\wandb-metadata.json
2023-05-08 10:49:24,033 INFO    wandb-upload_1:21796 [upload_job.py:push():137] Uploaded file D:\pycharm\Projects\DRL-MTSP-main\wandb\run-20230508_104917-tsapypnn\files\config.yaml
2023-05-08 10:49:24,903 ERROR   StreamThr :21796 [internal.py:wandb_internal():174] Thread HandlerThread:
Traceback (most recent call last):
  File "D:\Anaconda\envs\VRP\lib\site-packages\wandb\sdk\internal\internal_util.py", line 49, in run
    self._run()
  File "D:\Anaconda\envs\VRP\lib\site-packages\wandb\sdk\internal\internal_util.py", line 100, in _run
    self._process(record)
  File "D:\Anaconda\envs\VRP\lib\site-packages\wandb\sdk\internal\internal.py", line 279, in _process
    self._hm.handle(record)
  File "D:\Anaconda\envs\VRP\lib\site-packages\wandb\sdk\internal\handler.py", line 136, in handle
    handler(record)
  File "D:\Anaconda\envs\VRP\lib\site-packages\wandb\sdk\internal\handler.py", line 146, in handle_request
    handler(record)
  File "D:\Anaconda\envs\VRP\lib\site-packages\wandb\sdk\internal\handler.py", line 699, in handle_request_run_start
    self._tb_watcher = tb_watcher.TBWatcher(
  File "D:\Anaconda\envs\VRP\lib\site-packages\wandb\sdk\internal\tb_watcher.py", line 118, in __init__
    wandb.tensorboard.reset_state()
  File "D:\Anaconda\envs\VRP\lib\site-packages\wandb\sdk\lib\lazyloader.py", line 58, in __getattr__
    module = self._load()
  File "D:\Anaconda\envs\VRP\lib\site-packages\wandb\sdk\lib\lazyloader.py", line 33, in _load
    module = importlib.import_module(self.__name__)
  File "D:\Anaconda\envs\VRP\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Anaconda\envs\VRP\lib\site-packages\wandb\integration\tensorboard\__init__.py", line 3, in <module>
    from .log import _log, log, reset_state, tf_summary_to_dict  # noqa: F401
  File "D:\Anaconda\envs\VRP\lib\site-packages\wandb\integration\tensorboard\log.py", line 35, in <module>
    Summary = pb.Summary if pb else None
  File "D:\Anaconda\envs\VRP\lib\importlib\util.py", line 245, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "D:\Anaconda\envs\VRP\lib\site-packages\tensorboard\compat\proto\summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "D:\Anaconda\envs\VRP\lib\site-packages\tensorboard\compat\proto\tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "D:\Anaconda\envs\VRP\lib\site-packages\tensorboard\compat\proto\resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "D:\Anaconda\envs\VRP\lib\site-packages\tensorboard\compat\proto\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\63218\AppData\Roaming\Python\Python38\site-packages\google\protobuf\descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
